///////////////////////////////////////////////////////////////////////////////
// Simple batch: open files - revision 0.3
// jazz-y@ya.ru
///////////////////////////////////////////////////////////////////////////////

#target photoshop

/*
// BEGIN__HARVEST_EXCEPTION_ZSTRING
<javascriptresource>
<name>Simple batch: open files</name>
<category>jazzy</category>
</javascriptresource>
// END__HARVEST_EXCEPTION_ZSTRING
*/

strMessage = "Simple batch: open files"
strSource={ru: "Источник:", en: "Source:"}
strOpenFldr={ru: "открыть папку...", en: "open folder..."}
strActiveDocFldr={ru: "использовать папку активного документа", en: "get folder of active document"}
strFromBridge={ru: "получить файлы из Bridge", en: "get files form Bridge"}
strBrowse={ru: "Обзор...", en: "Browse..."}
strSubfolders={ru: "обрабатывать подкаталоги", en: "include all subfolders"}
strAcr={ru: "открывать RAW в ACR", en: "open RAW in ACR"}
strExt={ru: "открывать следующие типы файлов: ", en: "open following file types: "}
strCounter={ru: "количество файлов: ", en: "number of files: "}
strAllFiles={ru: "все файлы", en: "all files"}
strProgress={ru: "показывать прогресс-бар при открытии файлов", en: "show progress-bar while opening files"}
strOpen={ru: "Начать обработку", en: "Start processing"}
strCancel={ru: "Отмена", en: "Cancel"}
strBridgeList = {ru: "список файлов из Bridge", en: "Bridge file list"}
strStop={ru: "Превать обработку", en: "Stop processing"}
strErrBridge={ru: "Невозможно установить соединение с Bridge!", en: "Unable connect to Bridge!"}
strErrCounter={ru: "Выбрано слишком много файлов!", en: "Too many files selected!"}
strErrActive={ru: "Не найдена папка активного документа!", en: "Folder of active document not found!"}

var maxNumberOfFiles = 1000 // ограничение на максимальное количество файлов в каталоге/подкаталогах
$.localize = true 
//$.locale = "ru" 

eval("@JSXBIN@ES@2.0@MyBbyBnAVMhHbyBn0ABOhKbhMn0ACJhMnAEjzRjHjFjUiTjDjSjJjQjUiTjFjUjUj\
JjOjHjTBfRBjzIjTjFjUjUjJjOjHjTCfffOhPbhRn0ADJhRnASzBjXDAEjzLjCjVjJjMjEiXjJjOjEj\
PjXEfRBFcfffnftJyhRnASzGjSjFjTjVjMjUFBEXzEjTjIjPjXGfVDfAnfnftOhTbhVn0ADOhVbhXn0\
AFJhXnASzDjUjNjQHCEXzFjTjQjMjJjUIfXzIjGjJjMjFiMjJjTjUJfjCfRBFeBKffnftJhYnASzDjD\
jVjSKDEjzQjHjFjUiBjDjUjJjWjFiEjPjDiQjBjUjILfnfnftJhZnASzGjPjVjUjQjVjUMEAnnftOhb\
byhdn0ABahdbyhfn0ABOhfbyhfn0ABDhfnAzANfACzChdhdOQNfVHfCVzBjJPfFVKfDnnbyhfn0ABJy\
hfnAEXzEjQjVjTjIQfVMfERBQNfVHfCVPfFffAVPfFAXzGjMjFjOjHjUjIRfVHfCByBzBhcSAUzChGh\
GTCzBheUXRfVHfCnndACzChBhdVVKfDnnbnnnJiDnABXzFjUjPjUjBjMWfjCfCzBhLXXRfVMfEnndBn\
fACOXzKjTjPjVjSjDjFiNjPjEjFYfjCfnndBbiGn0ADJiGnASMEEXIfXJfjCfRBFeBKffnftJiHnABX\
WfjCfXRfVMfEnfOiJbyiLn0ABOiLbyiNn0ABJiNnAEXzQjEjPiGjPjSjDjFjEiQjSjPjHjSjFjTjTZf\
jzDjBjQjQgafRCFeAFeQjPjQjFjOiGjJjMjFhIjPjVjUjQjVjUhJffAEjzWjHjFjUiQjSjPjHjSjFjT\
jTiCjBjSiTjFjUjUjJjOjHjTgbfnfbyiQn0ABJiQnAEjzIjPjQjFjOiGjJjMjFgcfRBVMfEffACUXRf\
VMfEnndAnOiWbiYn0AFJiYnABXzJjMjBjTjUiEjPjDiJjEgdfjCfEjzOjHjFjUiBjDjUjJjWjFiEjPj\
DiJiEgefnfnfJiZnABXzLjGjJjMjFiDjPjVjOjUjFjSgffjCfCzBhNhAXWfjCfXRfVMfEnnnfJianAB\
XJfjCfEXzEjKjPjJjOhBfVMfERBFeBKffnfOicJicnAEjzGjEjFjMiFjWjUhCfnfAEjzGjDjIjLiFjW\
jUhDfnfnJidnAEjzGjBjEjEiFjWjUhEfnfACUXRfVMfEnndAnJjAnAEjzRjQjVjUiTjDjSjJjQjUiTj\
FjUjUjJjOjHjThFfRBjCfffACVVFfBnndCbyjBn0ABJjBnABjzLjJjTiDjBjOjDjFjMjMjFjEhGfnct\
fAhzBhBhHEjhDfnfbjFn0ADJjFnASDAEjEfRBFctffnftJyjFnASFBEXGfVDfAnfnftOjHbjJn0AGJj\
JnABXgdfjCfndAfJjKnABXgffjCfndAfJjLnABXJfjCfneAfJjNnAEjhCfnfJjPnAEjhFfRBjCfffJj\
SnAEjzEjNjBjJjOhIfnfACVVFfBnndCbyjTn0ABJjTnABjhGfnctfAhhHjzHjJjTiFjWjFjOjUhJfbj\
Yn0ACJjYnASzFjFjWjFjOjUhKGXzBhRhLfVzJjBjSjHjVjNjFjOjUjThMfHnftOjabjcn0AEJjcnAEj\
hCfnfJjenABXgdfjCfndAfJjfnABXgffjCfndAfJkAnABXJfjCfneAfACOVhKfGjzHjHiOjPjUjJjGj\
ZhNfnnbkDn0ACJkDnAEjBfRBjCfffOkGbkIn0AEJkInASMEEXIfXJfjCfRBFeBKffnftOkKbykMn0AB\
OkMbykOn0ABJkOnAEXZfjgafRCFeAFeQjPjQjFjOiGjJjMjFhIjPjVjUjQjVjUhJffAEjgbfnfbykRn\
0ABJkRnAEjgcfRBVMfEffACUXRfVMfEnndAnOkWbkYn0ADJkYnABXgffjCfChAXWfjCfXRfVMfEnnnf\
JkZnABXgdfjCfEjgefnfnfJkanABXJfjCfEXhBfVMfERBFeBKffnfACUXRfVMfEnndAbkdn0AEJkdnA\
BXgdfjCfndAfJkenABXgffjCfndAfJkfnABXJfjCfneAfJlBnAEjhCfnfJlDnAEjhFfRBjCfffAhhHE\
jzNjHjFjUiEjPjDjVjNjFjOjUiJiEhOfnfnAIP4F0AiAF4B0AiAM4E0AiAhK4G0AiAhM40BhAK4D0Ai\
AH4C0AiAD40BiABHAhIAlHMlKbyBnAEM2hfBbyBn0ADO2iBBb2iDBn0ADJ2iDBnASzDjGjPjMhPAEjz\
GiGjPjMjEjFjShQfRBXzIjMjBjTjUiQjBjUjIhRfjCfftnftJ2iEBnASzSjVjTjFjSiTjFjMjFjDjUj\
FjEiGjPjMjEjFjShSBEXzJjTjFjMjFjDjUiEjMjHhTfVhPfAnfnftO2iFBZ2iFBnAFcfAhhHVhSfBnA\
UTCOXYfjCfnndAhhHjzLjEjPiOjPjUiVjQjEjBjUjFhUfnnb2iJBn0ACO2iJBb2iLBn0ACJ2iLBnASh\
SBEjLfnfnftO2iNBb2iPBn0ACJ2iPBnAEjzFjBjMjFjSjUhVfRBjzMjTjUjSiFjSjSiBjDjUjJjWjFh\
WfffZ2iQBnAFcfACOVhSfBnnbby2iTBn0ABJ2iTBnAShSBEjhQfRBXzEjQjBjUjIhXfVhSfBffnffAC\
OXYfjCfnndBnO2iWBby2iYBn0ABO2iYBb2iaBn0AGJ2iaBnASzCjCjUhYCEjzKiCjSjJjEjHjFiUjBj\
MjLhZfntnftJ2ibBnABXzGjUjBjSjHjFjUhafVhYfCneGjCjSjJjEjHjFfJ2icBnABXzEjCjPjEjZhb\
fVhYfCCXCXnEXzIjUjPiTjUjSjJjOjHhcfjzSjHjFjUiGjJjMjFjTiGjSjPjNiCjSjJjEjHjFhdfnfe\
AnnneXhbhAjHjFjUiGjJjMjFjTiGjSjPjNiCjSjJjEjHjFhIhJhbnfJ2idBnABXzIjPjOiSjFjTjVjM\
jUhefVhYfCNyBnAM2idBbyBn0ACJ2ifBnASzKjGjJjMjFjTiBjSjSjBjZhfAEjzEjFjWjBjMiAfRBXh\
bfVzIjSjFjTjQjPjOjTjFiBfBffnftJ2jABnABjhSfVhffAnfACiB40BhAhf40BiABBANC2jBBnfJ2j\
DBnABXzHjPjOiFjSjSjPjSiCfVhYfCNyBnAM2jDBbyBn0ABJ2jEBnAEjhVfRBCXnXhbfVzDjFjSjSiD\
fAeHiFjSjSjPjShBKnffABiD40BhAB0ANC2jEBnfJ2jGBnAEXzEjTjFjOjEiEfVhYfCRBFd2lYLffAE\
XzJjJjTiSjVjOjOjJjOjHiFfjhZfRBFeGjCjSjJjEjHjFffb2jJBn0ACJ2jJBnAEjhVfRBjzMjTjUjS\
iFjSjSiCjSjJjEjHjFiGfffZ2jKBnAFcfACOXYfjCfnndCnO2jPBby2jRBn0ABJ2jRBnASFDEjzJjFj\
OjVjNiGjJjMjFjTiHfRBVhSfBffnftAVhSfBb2jUBn0ACJ2jUBnAShPAEjhQfRBXhRfjCfftnftO2jV\
Bby2jXBn0ABJ2jXBnASFDEjiHfRBVhPfAffnftAXzGjFjYjJjTjUjTiIfVhPfAb2jZBn0ADJ2jZBnAB\
XzEjUjFjYjUiJfjzGjTjUiQjBjUjIiKfBXhRfjCfneAfnfJ2jaBnABXiJfjzJjTjUiDjPjVjOjUjFjS\
iLfneAfJ2jbBnABXzHjFjOjBjCjMjFjEiMfjzCjPjLiNfncffO2jfBby2jfBn0ADJ2jfBnABXiJfjiK\
fBXhRfjCfBXiJfjiLfneAfnfnfJy2jfBnABXiMfjiNfncffZy2jfBnAFcfACOVFfDnncfby2jfBn0AB\
Zy2jfBnAFctAEF4D0AiAhP40BiAhS4B0AiAhY4C0AiAAEAzIjHjFjUiGjJjMjFjTiOA2kABM2kCBbyB\
n0APJ2kFBnASzKjSjFjBjEiGjSjPjNiGiTiPAdhhHVzGjGjJjMjUjFjSiQfHFctFcfnftJ2kGBnASiQ\
HdUzCjcjciRhhHViQfHCOViQfHjzLjTjUjSiBjMjMiGjJjMjFjTiSfnnnnjzViBjSjSjBjZiPjGiGjJ\
jMjFiFjYjUjFjOjTjJjPjOjTiTfARBViQfHfnffJ2kHBnASzJjTjIjPjSjUiMjJjTjUiUBARBjiSffn\
ftO2kJBby2kLBn0ABO2kLBb2kNBn0AEJ2kNBnABjzLjFjSjSiPjWjFjSjTjJjajFiVfncffJ2kOBnAB\
jzIjBjMjMiGjJjMjFjTiWfAnnfJ2kPBnAEjzMjGjJjOjEiBjMjMiGjJjMjFjTiXfRDVhSfGjiWfXzMj\
EjPiTjVjCjGjPjMjEjFjSjTiYfjCfffO2kQBby2kQBn0ACJ2kQBnABjiWfAnnfZy2kQBnAFcfAEjzIj\
DjIjFjDjLiFjSjSiZfnfnAViPfAnACVXYfjCfnndCby2kUBn0ABO2kUBb2kWBn0ADJ2kWBnABjiVfnc\
ffJ2kXBnABjiWfAnnfa2kZBb2kbBn0ACJ2kbBnASHDEjzEiGjJjMjFiafRBQNfVhSfGVPfCffnftO2k\
cBby2keBn0ABO2keBby2lABn0ABJ2lABnAEXQfjiWfRBVHfDffAhhHEjzIjJjTiGjPjMjEjFjSibfRB\
VHfDffb2lDBn0ACJ2lDBnAEjiXfRDVHfDjiWfXiYfjCfffO2lEBby2lEBn0ACJ2lEBnABjiWfAnnfZy\
2lEBnAFcfAEjiZfnfnAXiIfVHfDnAVPfCAXRfVhSfGByBSAViPfAnJ2lLBnASzFjGjJjMjFjTicEEXz\
FjTjMjJjDjFidfjiWfRBFdAffnftJ2lMBnASzJjGjJjMjFjTiUjPiEjPieFAnnfta2lNBb2lPBn0ACO\
2lPBnACzKjJjOjTjUjBjOjDjFjPjGifQNfVicfEVPfCjiafnnby2lPBn0ABJ2lPBnABQNfVicfEVPfC\
EjiafRBQNfVicfEVPfCffnfO2lQBJ2lQBnAEXQfViefFRBEXhcfQNfVicfEVPfCnfffAEjzQjJjTiGj\
JjMjFiPjOjFiPjGiUjIjFjTjFjAfRDQNfVicfEVPfCViQfHViUfBffnAVPfCAXRfVicfEByBSO2lTBb\
y2lVBn0ABO2lVBby2lXBn0ABJ2lXBnABXhRfjCfXzGjGjTiOjBjNjFjBfEjiafRBXzBhQjCfVhSfGff\
nfAEjibfRBEjiafRBXjCfVhSfGffffb2laBn0ACJ2laBnASHDXhXfEjiafRBXjCfVhSfGffnftJ2lbB\
nABXhRfjCfXjBfEjhQfRBVHfDffnfACifVhSfGjzFiBjSjSjBjZjDfnnby2ldBn0ABJ2ldBnABXhRfj\
CfXjBfVhSfGnfJ2lfBnABXJfjCfEXhBfViefFRBFeBKffnfO2mABby2mABn0ABJ2mABnABXiJfjiKfE\
jzLjTjIjPjSjUjFjOiQjBjUjIjEfRBXhRfjCfffnfACVXYfjCfnndCby2mABn0ABJy2mABnABXiJfji\
KfjzNjTjUjSiCjSjJjEjHjFiMjJjTjUjFfnfO2mCBby2mCBn0ABJ2mCBnABXiJfjiLfCXjzKjTjUjSi\
DjPjVjOjUjFjSjGfXRfViefFnnnfACVXRfViefFnndAby2mCBn0ABJy2mCBnABXiJfjiLfCXjjGfnne\
BhQnfO2mEBby2mEBn0ADJ2mEBnABjhUfnctfJy2mEBnABXzJjTjFjMjFjDjUjJjPjOjHfjzCjEjMjIf\
ndAfJy2mEBnABjhUfncffACOXYfjCfnndAnO2mFBby2mFBn0ABJ2mFBnABXiMfjiNfnctfACUXRfVie\
fFnndAby2mFBn0ABJy2mFBnABXiMfjiNfncffO2mHBb2mJBn0ADJ2mJBnAEXzJjSjFjNjPjWjFiBjMj\
MjJfjzHjEjMiUjZjQjFjTjKfnfa2mKBby2mMBn0ABJ2mMBnAEXzDjBjEjEjLfjjKfRCFeEjJjUjFjNQ\
NfViUfBVPfCffAVPfCAXRfViUfBByBSO2mPBby2mPBn0ABJ2mPBnABXjHfjjKfXzFjJjOjEjFjYjMfE\
XzEjGjJjOjEjNfjjKfRBXzMjMjBjTjUiGjJjMjFiUjZjQjFjOfjCfffnfAEXjNfjjKfRBXjOfjCfffb\
y2mPBn0ABJy2mPBnABXjHfjjKfndAfAViPfAnZ2mSBnAFctAIP4C0AiAhS40BhAiQ4B0AhAiP40BiAi\
U4B0AiAic4E0AiAie4F0AiAH4D0AiACGAiHA2mTBM2mVBbyBn0ACO2mXBb2mZBn0ADJ2mZBnABjiDfn\
cffJ2maBnAEjhVfRBjzNjTjUjSiFjSjSiDjPjVjOjUjFjSjPfffZ2mbBnAFctAjiDfnZ2mdBnAFcf0D\
iZA2meBM2nABbyBn0ACO2nCBby2nCBn0ABZ2nCBnAFcfAUTCVEXzLjMjBjTjUiJjOjEjFjYiPjGjQfX\
jBfVzBjTjRfARBFeBhOffnndyBCzChchdjSChAXRfXjBfVjRfAEXjQfXjBfVjRfARBFeBhOffnnnndF\
nnnZ2nDBnAFctABjR40BhAB0AibA2nEBhbJlOnAShUAncfftJlQnASDBEjzGiXjJjOjEjPjXjTfRBFe\
GjEjJjBjMjPjHftnftJlRnABXiJfVDfBjzKjTjUjSiNjFjTjTjBjHjFjUfnfJlSnABXzLjPjSjJjFjO\
jUjBjUjJjPjOjVfVDfBneGjDjPjMjVjNjOfJlTnABXzNjBjMjJjHjOiDjIjJjMjEjSjFjOjWfVDfBAR\
CFeEjGjJjMjMFeDjUjPjQfnfJlUnABXzHjTjQjBjDjJjOjHjXfVDfBndKfJlVnABXzHjNjBjSjHjJjO\
jTjYfVDfBndQfJlZnASzCjQjOjZCEXjLfVDfBREFeFjQjBjOjFjMjzJjVjOjEjFjGjJjOjFjEjafjja\
fWzGiPjCjKjFjDjUjbBzEjOjBjNjFjcFeCjQjOffnftJlanABXiJfVjZfCjzJjTjUjSiTjPjVjSjDjF\
jdfnfJlbnABXjVfVjZfCneGjDjPjMjVjNjOfJlcnABXjWfVjZfCARCFeEjGjJjMjMFeDjUjPjQfnfJl\
dnABXjXfVjZfCndKfJlenABXjYfVjZfCndKfJmCnASzFjHjSiGjMjEjeDEXjLfVjZfCRDFeFjHjSjPj\
VjQjjafWjbBjcFeFjHjSiGjMjEffnftJmDnABXjVfVjefDneDjSjPjXfJmEnABXjWfVjefDARCFeEjM\
jFjGjUFeGjDjFjOjUjFjSfnfJmFnABXjXfVjefDndKfJmGnABXjYfVjefDndAfJmInASzIjEjMifjBj\
SjSjBjZjfEARDjzLjTjUjSiPjQjFjOiGjMjEjSkAfjzQjTjUjSiBjDjUjJjWjFiEjPjDiGjMjEjSkBf\
jzNjTjUjSiGjSjPjNiCjSjJjEjHjFkCffnftJmJnASjIFEXjLfVjefDREFeMjEjSjPjQjEjPjXjOjMj\
JjTjUjjafjjafWjbCjcFeCjEjMzFjJjUjFjNjTkDVjffEffnftJmMnASzIjCjOiCjSjPjXjTjFkEGEX\
jLfVjefDREFeGjCjVjUjUjPjOjjafjjafWjbBjcFeIjCjOiCjSjPjXjTjFffnftJmNnABXiJfVkEfGj\
zJjTjUjSiCjSjPjXjTjFkFfnfJmRnASiKHEXjLfVjZfCREFeKjTjUjBjUjJjDjUjFjYjUjjafjjafWj\
bBjcFeGjTjUiQjBjUjIffnftJmSnABXiJfViKfHnehUhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQ\
hQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQhQfJmUnASzIjD\
jIiTjVjCjGjMjEkGIEXjLfVjZfCREFeIjDjIjFjDjLjCjPjYjjafjjafWjbBjcFeIjDjIiTjVjCjGjM\
jEffnftJmVnABXiJfVkGfIjzNjTjUjSiTjVjCjGjPjMjEjFjSjTkHfnfJmXnASzFjDjIiBjDjSkIJEX\
jLfVjZfCREFeIjDjIjFjDjLjCjPjYjjafjjafWjbBjcFeFjDjIiBjDjSffnftJmYnABXiJfVkIfJjzG\
jTjUjSiBjDjSkJfnfJmcnASzCjHjSkKKEXjLfVjZfCRDFeFjHjSjPjVjQjjafWjbBjcFeCjHjSffnft\
JmdnABXjVfVkKfKneDjSjPjXfJmenABXjWfVkKfKARCFeEjMjFjGjUFeEjGjJjMjMfnfJmfnABXjXfV\
kKfKndKfJnAnABXjYfVkKfKndAfJnCnASzLjTjUjBjUjJjDjUjFjYjUhRkLLEXjLfVkKfKREFeKjTjU\
jBjUjJjDjUjFjYjUjjafjjafWjbBjcFeLjTjUjBjUjJjDjUjFjYjUhRffnftJnDnABXiJfVkLfLjzGj\
TjUjSiFjYjUkMfnfJnFnASzNjEjMiUjZjQjFjTifjBjSjSjBjZkNMARBjiSffnftJnGnASjKNEXjLfV\
kKfKREFeMjEjSjPjQjEjPjXjOjMjJjTjUjjafjjafWjbCjcFeHjEjMiUjZjQjFjTkDVkNfMffnftJnH\
nABXjHfVjKfNndAfJnJnASiLOEXjLfVjZfCREFeKjTjUjBjUjJjDjUjFjYjUjjafjjafWjbBjcFeCjT\
jUffnftJnKnABXiJfViLfOCXjjGfnneLhQhQhQhQhQhPhQhQhQhQhQnfJnNnASzKjDjIiQjSjPjHjSj\
FjTjTkOPEXjLfVDfBREFeIjDjIjFjDjLjCjPjYjjafjjafWjbBjcFeKjDjIiQjSjPjHjSjFjTjTffnf\
tJnOnABXiJfVkOfPjzLjTjUjSiQjSjPjHjSjFjTjTkPfnfJnSnASzEjHjSiCjOkQQEXjLfVDfBRDFeF\
jHjSjPjVjQjjafWjbBjcFeEjHjSiCjOffnftJnTnABXjVfVkQfQneDjSjPjXfJnUnABXjWfVkQfQARC\
FeGjDjFjOjUjFjSFeGjDjFjOjUjFjSfnfJnVnABXjXfVkQfQndKfJnWnABXjYfVkQfQndAfJnYnASiN\
REXjLfVkQfQREFeGjCjVjUjUjPjOjjafjjafWjbBjcFeCjPjLffnftJnZnABXiJfViNfRjzHjTjUjSi\
PjQjFjOkRfnfJnbnASzGjDjBjOjDjFjMkSSEXjLfVkQfQREFeGjCjVjUjUjPjOjjafjjafWjbBjcFeG\
jDjBjOjDjFjMffnftJncnABXiJfVkSfSjzJjTjUjSiDjBjOjDjFjMkTfnfJnfnABXzHjPjOiDjMjJjD\
jLkUfVkEfGNyBnAMnfbyBn0ADJ2BBnASHAXYfjCfnftJ2CBnABXYfjCfndAfO2DBJ2DBnABXYfjCfVH\
fAnfACOEjiOfnfnncfnABH40BiAABANC2EBnfJ2GBnABXzIjPjOiDjIjBjOjHjFkVfVjIfFNyBnAM2G\
BbyBn0AEO2IBby2IBn0ABJ2IBnABXiMfjkEfncffACVXjMfXjHfezEjUjIjJjTkWfnndAby2IBn0ABJ\
y2IBnABXiMfjkEfnctfJ2KBnASHAXYfjCfnftJ2LBnABXYfjCfXjMfXjHfekWfnfO2MBb2OBn0AFJ2O\
BnASHAdCOVHfAXYfjCfnnFdAVHfAnffJ2PBnABjhUfnctfJy2PBnABXjHfekWfVHfAnfJy2PBnABXYf\
jCfVHfAnfJy2PBnABjhUfncffACOEjiOfnfnncfnABH40BiAABANC2RBnfJ2TBnABXkVfVjKfNNyBnA\
M2TBbyBn0ACJ2VBnABXjOfjCfXiJfXjHfekWfnfJ2WBnAEjiHfRCEjhQfRBXhRfjCfffXiJfXjHfekW\
fff0DNC2XBnfJ2gaBnABXkUfVkGfINyBnAM2gaBbyBn0AEJ2gaBnABXiYfjCfXzFjWjBjMjVjFkXfek\
WfnfJy2gaBnABjhUfnctfJy2gaBnAEjiOfnfJy2gaBnABjhUfncff0DNC2gaBnfJ2gbBnABXkUfVkIf\
JNyBnAM2gbBbyBn0ABJ2gbBnABXzFjEjPiBiDiSkYfjCfXkXfekWfnf0DNC2gbBnfJ2gcBnABXkUfVk\
OfPNyBnAM2gcBbyBn0ABJ2gcBnAEjzWjQjVjUiQjSjPjHjSjFjTjTiCjBjSiTjFjUjUjJjOjHjTkZfR\
BXkXfekWfff0DNC2gcBnfJ2geBnABXzGjPjOiTjIjPjXkafVDfBNyBnAM2geBbyBn0ABO2hABb2hCBn\
0AJJ2hCBnABjhUfnctfJ2hEBnABXYfjCfdUTCOXYfjCfnndBCOEjLfnfnnbnnFdAXYfjCfnfJ2hFBnA\
BXYfjCfdUThhHEXiFfjhZfRBFeGjCjSjJjEjHjFffCOXYfjCfnndCnnFdAXYfjCfnfJ2hHBnABXjHfj\
jIfXYfjCfnfJ2hIBnABXkXfjkGfXiYfjCfnfJ2hJBnABXkXfjkIfXkYfjCfnfJ2hKBnABXkXfjkOfEj\
gbfnfnfJ2hLBnABXiJfjiKfdCOXYfjCfnndCjjFfEjjEfRBXhRfjCfffnfJ2hOBnABjhUfncffAhhHj\
zJjGjSjPjNiFjWjFjOjUkbfb2hSBn0AKJ2hSBnABjhUfnctfJ2hTBnABXjHfjjIfXYfjCfnfJ2hUBnA\
BXkXfjkGfXiYfjCfnfJ2hVBnABXkXfjkIfXkYfjCfnfJ2hWBnABXkXfjkOfEjgbfnfnfJ2hXBnABXiJ\
fjiKfEjjEfRBXhRfjCfffnfJ2hYBnABXiMfjjZfncffJ2hZBnABXiMfjkEfncffJ2haBnABXiJfjiLf\
CXCXCXjjGfXgffjCfnnnneBicXWfjCfnnnfJ2hbBnABXiJfjiNfjzHjTjUjSiTjUjPjQkcfnf0DNC2h\
dBnfZ2nGBnAVDfBAUkb40BhAhU40BiAjZ4C0AiAje4D0AiAjf4E0AiAjI4F0AiAkE4G0AiAiK4H0AiA\
kG4I0AiAkI4J0AiAkK4K0AiAkL4L0AiAkN4M0AiAjK4N0AiAiL4O0AiAkO4P0AiAkQ4Q0AiAiN4R0Ai\
AkS4S0AiAD4B0AiABTAEA2nHBM2nJBbyBn0ADJ2nLBnASzHjDjPjVjOjUjFjSkdAndAftJ2nMBnASzD\
jMjFjOkeBXRfVicfInfta2nNBb2nPBn0AEJ2nPBnASKDEjiafRBEXzFjTjIjJjGjUkffVicfInfffnf\
tO2nQBb2nSBn0AFJ2nSBnASjREEjzLjHjFjUiGjJjMjFiOjBjNjFlAfRBVKfDffnftJ2nTBnASWFXWf\
jCfnftJ2nUBnASzHjDjVjSjSjFjOjUlBGCXChAVWfFCXXRfVicfInndBnnnndBnftJ2nVBnAEXzOjVj\
QjEjBjUjFiQjSjPjHjSjFjTjTlCfjgafRCVlBfGVWfFffJ2nWBnAEXzSjDjIjBjOjHjFiQjSjPjHjSj\
FjTjTiUjFjYjUlDfjgafRBCXCXCXCXVlBfGnneBicVWfFnnnneChahAVjRfEnnffAEjgbfnfng2nZBb\
yBn0ACO2nbBby2ndBn0ABJ2ndBnAEjzNjPjQjFjOiDjBjNjFjSjBiSjBjXlEfRCVKfDXkYfjCfffAUT\
XkYfjCfEjjAfRCVKfDjzUiBjSjSjBjZiPjGiSjBjXiFjYjUjFjOjTjJjPjOjTlFfffnnby2ACn0ABJ2\
ACnAEXzEjPjQjFjOlGfjgafRBVKfDffD2CCnANtABnzBjFlHnbyBn0ABJ2DCnATkdyBBtO2FCb2HCn0\
AGJ2HCnASkeBXRfVicfInfta2ICby2ICn0ABJ2ICnASHHEXkffVicfInfnftAVPfCAVkefBByBSJ2JC\
nABXgdfjCfndAfJ2KCnABXgffjCfndAfJ2LCnABXJfjCfneAfD2MCnANtACzChehdlIVkdfAnndCnAV\
PfCAVkefBByBSAJP4C0AiAW4F0AiAjR4E0AiAlB4G0AiAK4D0AiAic40BhAH4H0AiAkd40BiAke4B0A\
iABIAgcA2PCM2RCbyBn0ABg2TCbyBn0AEJ2VCnASzDjSjFjGlJAEjzPiBjDjUjJjPjOiSjFjGjFjSjF\
jOjDjFlKfntnftJ2WCnAEXzLjQjVjUiQjSjPjQjFjSjUjZlLfVlJfARCjzJjHiQjSjPjQjFjSjUjZlM\
fjzOjHiGjJjMjFiSjFjGjFjSjFjOjDjFlNfffJ2XCnAEXzNjQjVjUiFjOjVjNjFjSjBjUjFjElOfVlJ\
fARDjzJjHiEjPjDjVjNjFjOjUlPfjzIjHiPjSjEjJjOjBjMlQfjzLjHiUjBjSjHjFjUiFjOjVjNlRff\
fZ2YCnAEXzHjHjFjUiQjBjUjIlSfEjzQjFjYjFjDjVjUjFiBjDjUjJjPjOiHjFjUlTfRBVlJfAffRBj\
lNfffABnlHnbyBn0ABZ2ZCnAFbABlJ40BiAABALA2gaCM2gcCbyBn0AEJ2geCnASlJAEjlKfntnftJ2\
gfCnAEXlLfVlJfARCjlMfjzLjHiEjPjDjVjNjFjOjUiJiElUfffJ2hACnAEXlOfVlJfARDjlPfjlQfj\
lRfffgy2hBCbyBn0ABZ2hBCnAEXzKjHjFjUiJjOjUjFjHjFjSlVfEjlTfRBVlJfAffRBjlUfffABnlH\
nbyBn0ABZy2hBCnAFd0ABlJ40BiAABAgeA2hCCM2hECbyBn0AGJ2hGCnASlJAEjlKfntnftJ2hHCnAE\
XlLfVlJfARCjlMfjzSjHiOjVjNjCjFjSiPjGiEjPjDjVjNjFjOjUjTlWfffJ2hICnAEXlOfVlJfARDj\
zMjHiBjQjQjMjJjDjBjUjJjPjOlXfjlQfjlRfffJ2hJCnASkeBEXlVfEjlTfRBVlJfAffRBjlWfffnf\
ta2hLCb2hMCn0AEJ2hMCnASlJAEjlKfntnftJ2hNCnAEXlLfVlJfARCjlMfjlUfffJ2hOCnAEXzIjQj\
VjUiJjOjEjFjYlYfVlJfARCjlPfVPfCffO2hQCZ2hQCnAFctACOEXlVfEjlTfRBVlJfAffRBjlUfffX\
gdfjCfnnnAVPfCBVkefBByBjSZ2hTCnAFcfADP4C0AiAlJ40BiAke4B0AiAADAhOA2hUCM2hWCbyBn0\
ADJ2hYCnASzPjGjJjMjFiGjPjMjEjFjSiBjSjSjBjZlZAEXiOfEjhQfRBVzMjTjSjDiGjPjMjEjFjSi\
TjUjSlafDffnfnfta2hZCb2hbCn0ADO2hbCby2hbCn0ACJ2hbCnABjiDfnctfZy2hbCnAnAClIXRfVz\
JjEjFjTjUiBjSjSjBjZlbfEjzQjNjBjYiOjVjNjCjFjSiPjGiGjJjMjFjTlcfnnnJ2hdCnASzLjGjJj\
MjFiGjPjMjEiPjCjKldCQNfVlZfAVPfBnftO2heCby2hfCn0ABO2hfCJ2hfCnAEXQfVlbfERBVldfCf\
fAhhHXzGjIjJjEjEjFjOlefVldfCnACifVldfCjiafnnby2iBCn0ABO2iBCJ2iBCnAEjiXfRDEXhcfV\
ldfCnfVlbfEVzNjVjTjFiTjVjCjGjPjMjEjFjSjTlffFffAVlffFnAVPfBAXRfVlZfAByBSZ2iECnAV\
lbfEAGP4B0AiAla40BhAlb4B0AhAlf4C0AhAlZ40BiAld4C0AiADDAiXA2iFCM2iHCbyBn0AHJ2iJCn\
ASHAEXzLjUjPiVjQjQjFjSiDjBjTjFmAfXjBfVzIjGjJjMjFiOjBjNjFmBfEnfnftJ2iKCnASzHjMjB\
jTjUiEjPjUmCBEXjQfVHfARBFeBhOffnftO2iLCZ2iLCnAFcfACOVmCfBnndyBnJ2iNCnASzJjFjYjU\
jFjOjTjJjPjOmDCEXzGjTjVjCjTjUjSmEfVHfARCCXVmCfBnndBChAXRfVHfAVmCfBnnffnftO2iPCb\
y2iRCn0ABa2iRCby2iTCn0ABO2iTCby2iVCn0ABZ2iVCnAFctACOVmDfCQNfVzNjTjIjPjSjUjDjVjU\
iBjSjSjBjZmFfGVPfDnnnAVPfDAXRfVmFfGByBSACifVmFfGjjDfnnby2iYCn0ABJ2iYCnASmFGAnnf\
fa2iaCby2icCn0ABO2icCb2ieCn0ACJ2ieCnAEXQfVmFfGRBVmDfCffZ2ifCnAFctACOVmDfCQNfVzR\
jBjSjSjBjZiPjGiFjYjUjFjOjTjJjPjOjTmGfFVPfDnnnAVPfDAXRfVmGfFByBSZ2jDCnAFcfAHP4D0\
AiAmB40BhAmG4B0AhAmF4C0AhAmC4B0AiAmD4C0AiAH40BiADEAjAA2jECM2jGCbyBnABM2jLCbyBn0\
AEJ2jNCnAEXzHjXjSjJjUjFjMjOmHfjzBhEmIfRBFeBhAffJ2jOCnASzBjMmJAXzFjDjPjVjOjUmKfV\
zBjEmLfFnftO2jPCby2jQCn0ABO2jQCZ2jQCnAnAUTEXzGjIjBjTiLjFjZmMfVmLfFRBjzIjHiNjFjT\
jTjBjHjFmNfffCVVjRfGEXzJjHjFjUiTjUjSjJjOjHmOfVmLfFRBjmNfffnnnnnAVmJfAna2jSCb2jT\
Cn0AEJ2jTCnASzBjLmPCEXzGjHjFjUiLjFjZmQfVmLfFRBVPfBffnftJ2jUCnASzBjUmRDEXzHjHjFj\
UiUjZjQjFmSfVmLfFRBVmPfCffnftJ2jVCnABjzEjTjUjSjLmTfEXzQjUjZjQjFiJiEiUjPiTjUjSjJ\
jOjHiJiEmUfjgafRBVmPfCffnfc2jWCnAVmRfDDRBXzLiCiPiPiMiFiBiOiUiZiQiFmVfjzNiEjFjTj\
DiWjBjMjVjFiUjZjQjFmWffRBXzKiTiUiSiJiOiHiUiZiQiFmXfjmWffRBXzLiJiOiUiFiHiFiSiUiZ\
iQiFmYfjmWffDb2jYCn0ACJ2jYCnABQNfVzBjPmZfEjmTfEXzKjHjFjUiCjPjPjMjFjBjOmafVmLfFR\
BVmPfCffnfD2jZCnANtb2jbCn0ACJ2jbCnABQNfVmZfEjmTfEXmOfVmLfFRBVmPfCffnfD2jcCnANtb\
2jeCn0ACJ2jeCnABQNfVmZfEjmTfEXzJjHjFjUiEjPjVjCjMjFmbfVmLfFRBVmPfCffnfD2jfCnANtA\
VPfBAVmJfAByBSAHP4B0AiAjR4C0AhAmR4D0AiAmL4B0AhAmZ40BhAmJ40BiAmP4C0AiADEAzSjEjFj\
TjDjSjJjQjUjPjSiUjPiPjCjKjFjDjUmcA2kCCBg2jICbyBn0ACJ2jICnASmLAEXzQjHjFjUiDjVjTj\
UjPjNiPjQjUjJjPjOjTmdfjgafRBjzEiHiViJiEmefffnftO2jJCJ2jJCnAEjmcfRDVzLjTjFjUjUjJ\
jOjHjTiPjCjKmffBVmLfAjjUfffACVVmLfAjjafnnnABnlHnnACmf40BhAmL40BiABBABA2kECM2kGC\
byBnABM2kLCbyBn0AFJ2kNCnASmLAEjzQiBjDjUjJjPjOiEjFjTjDjSjJjQjUjPjSnAfntnftJ2kOCn\
ASmJBXRfXzKjQjSjPjQjFjSjUjJjFjTnBfXzHjSjFjGjMjFjDjUnCfVmZfFnftJ2kPCnAEXzJjQjVjU\
iTjUjSjJjOjHnDfVmLfARCjmNfVjRfGffa2kQCb2kRCn0AFJ2kRCnASmPDEXhcfQNfXnBfXnCfVmZfF\
VPfCnfnftO2kSCD2kSCnANfAUiRUiRUiRCOVmPfDnneJififjQjSjPjUjPififCOVmPfDnneJififjD\
jPjVjOjUififnnCOVmPfDnneJififjDjMjBjTjTififnnCOVmPfDnneHjSjFjGjMjFjDjUnnnJ2kTCn\
ASzBjWnEEQNfVmZfFVmPfDnftJ2kUCnASmPDEXzQjTjUjSjJjOjHiJiEiUjPiUjZjQjFiJiEnFfjgaf\
RBVmPfDffnffc2kVCnAizGjUjZjQjFjPjGnGVnEfEERBFeHjCjPjPjMjFjBjOfRBFeGjTjUjSjJjOjH\
fRBFeGjOjVjNjCjFjSfRBnfEby2kWCn0ACJ2kWCnAEXzKjQjVjUiCjPjPjMjFjBjOnHfVmLfARCVmPf\
DVnEfEffDy2kWCnANtby2kXCn0ACJ2kXCnAEXnDfVmLfARCVmPfDVnEfEffDy2kXCnANtby2kYCn0AC\
J2kYCnAEXzKjQjVjUiJjOjUjFjHjFjSnIfVmLfARCVmPfDVnEfEffDy2kYCnANtby2kZCn0ACJ2kZCn\
AEXmHfjmIfRBinGVnEfEffDy2kZCnANtAVPfCAVmJfBByBSZ2kcCnAVmLf0AHP4C0AiAjR4B0AhAnE4\
E0AiAmL40BiAmZ40BhAmJ4B0AiAmP4D0AiACFAzSjPjCjKjFjDjUiUjPiEjFjTjDjSjJjQjUjPjSnJA\
2kdCCJ2kICnASmLAEjnJfRCVmffBjjUfffnftJ2kJCnAEXzQjQjVjUiDjVjTjUjPjNiPjQjUjJjPjOj\
TnKfjgafRCjmefVmLfAffACmf40BhAmL40BiABBAhFA2keCM2lACbyBn0AJJ2lCCnABXYfVzKjFjYjQ\
jPjSjUiJjOjGjPnLfAndAfJ2lDCnABXhRfVnLfAneAfJ2lECnABXiYfVnLfAnctfJ2lFCnABXkYfVnL\
fAnctfJ2lGCnABXJfVnLfAneAfJ2lHCnABXgffVnLfAndAfJ2lICnABXWfVnLfAndAfJ2lJCnABXgdf\
VnLfAndAfJ2lKCnABXjOfVnLfAneAfABnL40BhAB0AzOjJjOjJjUiFjYjQjPjSjUiJjOjGjPnMA2lLC\
M2lNCbyBn0ADO2lQCby2lQCn0ACJ2lQCnASjRFEXIfVjRfFRBFeBicffnffJy2lQCnASzDjXjJjOnNA\
nctffACVEXzHjJjOjEjFjYiPjGnOfVjRfFRBFeBicffnndyBby2lQCn0ACJy2lQCnASjRFEXIfVjRfF\
RBFeChPhPffnffJy2lQCnASnNAncfffO2lSCb2lUCn0AIJ2lUCnASkeBXRfQNfVjRfFChAXRfVjRfFn\
ndBnftJ2lVCnASMCAnnftJ2lWCnASzGjDjVjSiMjFjOnPDndAftJ2lYCnAEXQfVMfCRBXjCfVjRfFff\
J2lZCnASnPDXRfXjCfVjRfFnffa2lbCby2ldCn0ABO2ldCby2lfCn0ACJ2lfCnAEXQfVMfCRBQNfVjR\
fFVPfEffJy2lfCnASnPDCXnXRfQNfVjRfFVPfEnnntfACSCXCXVnPfDXRfQNfVjRfFVPfEnnVkefBnn\
nndhIb2mCCn0ACJ2mCCnAEXQfVMfCRBFeDhOhOhOffD2mDCnANtAVPfEBChAXRfVjRfFnndBByBSJ2m\
GCnAEXQfVMfCRBQNfVjRfFChAXRfVjRfFnndBffO2mICby2mICn0ABJ2mICnASjRFEXhBfVMfCRBFeB\
icffnffAVnNfAJy2mICnASjRFEXhBfVMfCRBFeChPhPffnffACUXRfVjRfFnndBnZ2mLCnAVjRfFAGP\
4E0AiAM4C0AiAjR40BhAnN40BiAnP4D0AiAke4B0AiABFAjEA2mMCM2mOCbyBn0ADJ2mQCnASjRAXjB\
fEjiafRBVjRfAffnffO2mRCby2mRCn0ABJ2mRCnASjRAEXIfVjRfARBFeBicffnffACVEXnOfVjRfAR\
BFeBicffnndyBby2mRCn0ABJy2mRCnASjRAEXIfVjRfARBFeChPhPffnffZ2mTCnAQNfVjRfAChAXRf\
VjRfAnndBABjR40BhAB0AlAA2mUCM2mWCbyBn0AFJ2mYCnASzMjJjOiEjJjBjMjPjHiNjPjEjFnQCdU\
iRCOVnQfCjjafnnCOVnQfCnncfnnXzCiOiPnRfjzLiEjJjBjMjPjHiNjPjEjFjTnSfXzDiBiMiMnTfj\
nSfnffJ2mZCnASzEjEjFjTjDnUAEjnAfntnftJ2maCnAEXzHjQjVjUiQjBjUjInVfVnUfARCjzFjHiO\
jVjMjMnWfEjiafRBVmBfBffffJ2mbCnAEXnHfVnUfARCjzNjHiPjWjFjSjSjJjEjFiPjQjFjOnXfFct\
ffJ2mcCnAEjzNjFjYjFjDjVjUjFiBjDjUjJjPjOnYfRDjzFjHiPjQjFjOnZfVnUfAVnQfCffADmB40B\
hAnQ4B0AhAnU40BiACBAlEA2mdCM2mfCbyBn0AGJ2nBCnAEjhCfnfJ2nDCnABXzQjOjPjUjJjGjJjFj\
SjTiFjOjBjCjMjFjEnafjgafnctfJ2nECnASzLjIjBjOjEjMjFjSiGjJjMjFnbAEjiafRBXmBfjmIff\
fnftJ2nFCnAEXjLfXzJjOjPjUjJjGjJjFjSjTncfjgafRCFeEiOjUjGjZVnbfAffJ2nGCnAEXjLfXnc\
fjgafRCFeEiDjMjThAVnbfAffJ2nHCnAEXjLfXncfjgafRCFeEiQjMjZhAVnbfAffABnb40BiAABAhE\
A2nICM2nKCbyBn0ABa2nMCb2nOCn0ACJ2nOCnASzDjOjUjGndBQNfXncfjgafVPfAnftO2nPCby2nPC\
n0ACJ2nPCnAEXzGjSjFjNjPjWjFnefVndfBnfJy2nPCnATPAyBtACOXjcfXzJjFjWjFjOjUiGjJjMjF\
nffVndfBXjcfEjiafRBXmBfjmIfffnnnAVPf0AXRfXncfjgafByBSACP40BiAnd4B0AiAACAhCA2nRC\
M2nTCbyBn0ACa2nVCb2nXCn0ACJ2nXCnASndBQNfXncfjgafVPfAnftO2nYCby2nYCn0ABZ2nYCnAFc\
tACOXjcfXnffVndfBXjcfEjiafRBXmBfjmIfffnnnAVPf0AXRfXncfjgafByBSZ2nbCnAFcfACP40Bi\
And4B0AiAACAhDA2ncCM2neCbyBn0ABZ2neCnAEjnFfRBVjRfAffABjR40BhAB0AzDjThSjU2ABA2ne\
CM2nfCbyBn0ABZ2nfCnAEjmUfRBVmRfAffABmR40BhAB0AzDjUhSjT2BBA2nfCM2BDbyBn0ADJ2DDnA\
SmLAEjnAfntnftJ2EDnAEXnHfVmLfARCEj2ABfRBjjUfffVzDjWjBjM2CBfBffJ2FDnAEXnKfjgafRC\
FeLjQjSjPjHjSjFjTjTiCjBjSVmLfAffACmL40BiA2CB40BhABBAkZA2GDM2IDbyBn0ABg2KDbyBn0A\
CJ2KDnASmLAEXmdfjgafRBFeLjQjSjPjHjSjFjTjTiCjBjSffnftZ2LDnAEXmafVmLfARBEj2ABfRBj\
jUfffffABnlHnbyBn0ABZy2LDnAFcfABmL40BiAABAgbA2MDZJAnABjlPfEj2ABfRBFeIjEjPjDjVjN\
jFjOjUffnfJBnABjlQfEj2ABfRBFeHjPjSjEjJjOjBjMffnfJCnABjlMfEj2ABfRBFeIjQjSjPjQjFj\
SjUjZffnfJDnABjlNfEj2ABfRBFeNjGjJjMjFiSjFjGjFjSjFjOjDjFffnfJEnABjlRfEj2ABfRBFeK\
jUjBjSjHjFjUiFjOjVjNffnfJFnABjlUfEj2ABfRBFeKjEjPjDjVjNjFjOjUiJiEffnfJGnABjlWfEj\
2ABfRBFeRjOjVjNjCjFjSiPjGiEjPjDjVjNjFjOjUjTffnfJHnABjlXfEj2ABfRBFeLjBjQjQjMjJjD\
jBjUjJjPjOffnfJInABjhNfEj2ABfRBFeGjOjPjUjJjGjZffnfJJnABjmNfEj2ABfRBFeHjNjFjTjTj\
BjHjFffnfJKnABjnWfEj2ABfRBFeEjOjVjMjMffnfJLnABjnXfEj2ABfRBFeMjPjWjFjSjSjJjEjFiP\
jQjFjOffnfJMnABjnZfEj2ABfRBFeEjPjQjFjOffnfJOnABjmefnehEjGjBhShQhVhQhSjBhNhZhYhU\
jChNhUjGjCjEhNjBjEhZjChNjBjCjBhZjGhVjDhThYjGhWhRfJPnASiTyBARhcFeDiQiTiEFeDiQiEi\
EFeEiQiTiEiUFeDiQiTiCFeDiCiNiQFeDiSiMiFFeDiEiJiCFeDiHiJiGFeDiFiQiTFeDiJiGiGFeDi\
UiEiJFeDiKiQiHFeEiKiQiFiHFeDiKiQiFFeDiKiQiGFeDiKiQiYFeDiKiQhSFeDiKhSiDFeDiKhSiL\
FeDiKiQiDFeDiKiQiTFeDiNiQiPFeDiQiDiYFeDiQiEiGFeDiQiEiQFeDiSiBiXFeDiQiYiSFeDiQiO\
iHFeDiTiDiUFeDiUiHiBFeDiWiEiBFeDiJiDiCFeDiWiTiUFeDiUiJiGFeEiUiJiGiGFeDiQiCiNFeD\
iQiHiNFeDiQiQiNFeDiQiOiNFeDiQiGiNFeDiQiBiNFeDiEiDiNFeDiEiDhTFeDiEiJiDFeDiUiJiGF\
eDiDiSiXFeDiOiFiGFeDiSiBiGFeDiPiSiGFeDiNiSiXFeDiEiDiSFeDiNiPiTFeDiTiSiGFeDiQiFi\
GFeDiEiDiSFeDiDiShSFeDiEiOiHFeDiFiSiGFeDiYhTiGFeDiSiBiXfnftJSnASlFyBARQFeDiUiJi\
GFeDiDiSiXFeDiOiFiGFeDiSiBiGFeDiPiSiGFeDiNiSiXFeDiEiDiSFeDiNiPiTFeDiTiSiGFeDiQi\
FiGFeDiEiDiSFeDiDiShSFeDiEiOiHFeDiFiSiGFeDiYhTiGFeDiSiBiXfnftJUnASiDyBncfftJVnA\
ShGyBncfftJWnAShJyBnctftJXnASiWyBAnnftJganASCyBEjjbfntnftJgbnAEjnMfRBVCfyBffgyg\
fbyBn0ABOgfJgfnAShJyBncfffACOXRfjhMfnndAnABnlHnbyBn0ABJygfnAShJyBncfffOhAbyhAn0\
ABJhAnAEjhIfRBjhMfffAVhJfyBbyhAn0ABJyhAnAEjhIfnfJhDnAdVhGfyBFeGjDjBjOjDjFjMjjaf\
AHiD4C0AiAiW4F0AiAiT40BiAlF4B0AiAhG4D0AiAhJ4E0AiAC4G0AiAAHANByB")


function getFilesFromBridge(){var files=[];var len=app.document.selections.length;
if (len==0) {files.push (app.document.presentationPath)}{for (var i=0; i<len; i++){files.push (app.document.selections[i].path);}} return files.toSource()}